import AuthContextProvider from "@/modules/auth_provider";
import "./globals.css";
import WebSocketProvider from "@/modules/websocket_provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <WebSocketProvider>
            <div className="flex flex-col md:flex-row h-full min-h-screen font-sans">
              {children}
            </div>
          </WebSocketProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
